# Generated by Django 4.2.1 on 2023-05-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-priority', 'created_date']},
        ),
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='low', max_length=20),
        ),
    ]
